### ISSUE TITLE
About controlnext-svd_v2-unet-fp16_converted.safetensors and controlnext-svd_v2-unet-fp16.safetensors

### ISSUE THREAD

**Issue by Paddypan993** [kijai/ComfyUI-ControlNeXt-SVD-Wrapper#11]
I am here https://huggingface.co/Kijai/ControlNeXt-SVD-V2-Comfy/tree/main downloaded two models，I would like to know the difference between the controllext-svd-v2-unet-fp16-coverted.safesensors and the controllext-svd-v2-unet-fp16. safetensors. When I load the model using the Load Diffusion Model node, the controllext-svd-v2-unet-fp16-coverted.safesensors can be used normally, but when I load the controllext-svd-v2-unet-fp16. safetensors model, an error message will appear: raise Runtime Error ("ERROR: Could not detect model type of: {}". format (unet_path)). Is there any difference in the types of these two models? I would like to know the conversion rules, thank you

**Comment by kijai** [comment]
The "converted" version is meant to be used with the Load Diffusion Model as you noticed, the other one is the original and it can be used with the diffusers wrapper version, there are example workflows for both included in the examples -folder.

**Comment by Paddypan993** [comment]
> The "converted" version is meant to be used with the Load Diffusion Model as you noticed, the other one is the original and it can be used with the diffusers wrapper version, there are example workflows for both included in the examples -folder.

Thank you for your response. I also want to know if these two models were trained on different networks (with the same structure but different layers names), or were they transformed through certain map rules?

**Comment by kijai** [comment]
> > The "converted" version is meant to be used with the Load Diffusion Model as you noticed, the other one is the original and it can be used with the diffusers wrapper version, there are example workflows for both included in the examples -folder.
> 
> Thank you for your response. I also want to know if these two models were trained on different networks (with the same structure but different layers names), or were they transformed through certain map rules?

Same exact model, just the state_dict converted from diffusers to comfy compatible format, so just remapped.

**Comment by Paddypan993** [comment]
> > > The "converted" version is meant to be used with the Load Diffusion Model as you noticed, the other one is the original and it can be used with the diffusers wrapper version, there are example workflows for both included in the examples -folder.
> > 
> > 
> > Thank you for your response. I also want to know if these two models were trained on different networks (with the same structure but different layers names), or were they transformed through certain map rules?
> 
> Same exact model, just the state_dict converted from diffusers to comfy compatible format, so just remapped.

Thank you for your patient response
